# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-11 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20190308_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content_markdown',
            field=models.CharField(default=None, max_length=2000, verbose_name='markdown内容'),
            preserve_default=False,
        ),
    ]
